export const ALL_CELEBRITY_REQUEST = "ALL_CELEBRITY_REQUEST";
export const ALL_CELEBRITY_SUCCESS = "ALL_CELEBRITY_SUCCESS";
export const ALL_CELEBRITY_FAIL = "ALL_CELEBRITY_FAIL";

export const ALL_CELEBRITY_ROLE_OF_A_MOVIE_REQUEST = "ALL_CELEBRITY_ROLE_OF_A_MOVIE_REQUEST";
export const ALL_CELEBRITY_ROLE_OF_A_MOVIE_SUCCESS = "ALL_CELEBRITY_ROLE_OF_A_MOVIE_SUCCESS";
export const ALL_CELEBRITY_ROLE_OF_A_MOVIE_FAIL = "ALL_CELEBRITY_ROLE_OF_A_MOVIE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";