export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST";
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS";
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const ALL_REVIEW_OF_MOVIE_REQUEST = "ALL_REVIEW_OF_MOVIE_REQUEST";
export const ALL_REVIEW_OF_MOVIE_SUCCESS = "ALL_REVIEW_OF_MOVIE_SUCCESS";
export const ALL_REVIEW_OF_MOVIE_FAIL = "ALL_REVIEW_OF_MOVIE_FAIL";

export const NEW_MOVIE_REQUEST = "NEW_MOVIE_REQUEST";
export const NEW_MOVIE_SUCCESS = "NEW_MOVIE_SUCCESS";
export const NEW_MOVIE_FAIL = "NEW_MOVIE_FAIL";

export const NEW_ROLE_REQUEST = "NEW_ROLE_REQUEST";
export const NEW_ROLE_SUCCESS = "NEW_ROLE_SUCCESS";
export const NEW_ROLE_FAIL = "NEW_ROLE_FAIL";

export const NEW_CELEBRITY_REQUEST = "NEW_CELEBRITY_REQUEST";
export const NEW_CELEBRITY_SUCCESS = "NEW_CELEBRITY_SUCCESS";
export const NEW_CELEBRITY_FAIL = "NEW_CELEBRITY_FAIL";

export const ADD_CELEBRITY_ROLE_REQUEST = "ADD_CELEBRITY_ROLE_REQUEST";
export const ADD_CELEBRITY_ROLE_SUCCESS = "ADD_CELEBRITY_ROLE_SUCCESS";
export const ADD_CELEBRITY_ROLE_FAIL = "ADD_CELEBRITY_ROLE_FAIL";

export const ADD_MOVIE_CELEBRITY_REQUEST = "ADD_MOVIE_CELEBRITY_REQUEST";
export const ADD_MOVIE_CELEBRITY_SUCCESS = "ADD_MOVIE_CELEBRITY_SUCCESS";
export const ADD_MOVIE_CELEBRITY_FAIL = "ADD_MOVIE_CELEBRITY_FAIL";

export const ADD_MOVIE_ROLE_REQUEST = "ADD_MOVIE_ROLE_REQUEST";
export const ADD_MOVIE_ROLE_SUCCESS = "ADD_MOVIE_ROLE_SUCCESS";
export const ADD_MOVIE_ROLE_FAIL = "ADD_MOVIE_ROLE_FAIL";

export const ADD_MOVIE_CELEBRITY_ROLE_REQUEST = "ADD_MOVIE_CELEBRITY_ROLE_REQUEST";
export const ADD_MOVIE_CELEBRITY_ROLE_SUCCESS = "ADD_MOVIE_CELEBRITY_ROLE_SUCCESS";
export const ADD_MOVIE_CELEBRITY_ROLE_FAIL = "ADD_MOVIE_CELEBRITY_ROLE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";